export interface StreamRecording {
  id: string
  streamId: string
  title: string
  description?: string
  thumbnailUrl?: string
  recordingUrl: string
  duration: number // in seconds
  fileSize: number // in bytes
  startTime: string // ISO date string
  endTime?: string // ISO date string
  isProcessing: boolean
  isPublic: boolean
  viewCount: number
  downloadCount: number
  highlights: StreamHighlight[]
  chapters: StreamChapter[]
  quality: "low" | "medium" | "high" | "source"
  format: "mp4" | "webm"
}

export interface StreamChapter {
  id: string
  title: string
  startTime: number // in seconds
  endTime?: number // in seconds
  thumbnailUrl?: string
  productIds?: string[] // products featured in this chapter
}

export interface StreamHighlight {
  id: string
  title: string
  startTime: number // in seconds
  endTime: number // in seconds
  thumbnailUrl?: string
  clipUrl?: string
  viewCount: number
  createdBy: string // user who created the highlight
  isAutoGenerated: boolean
}

export interface DVRState {
  isEnabled: boolean
  bufferDuration: number // in seconds
  currentPosition: number // in seconds
  isRewinding: boolean
  playbackSpeed: number // 1.0 = normal speed
  availableQualities: string[]
  currentQuality: string
}

export interface RecordingControls {
  isRecording: boolean
  isPaused: boolean
  recordingDuration: number // in seconds
  autoRecord: boolean
  recordQuality: "low" | "medium" | "high" | "source"
  saveToCloud: boolean
  createHighlights: boolean
}
